### ISSUE TITLE
Problem displaying absolute text over carousel

### ISSUE THREAD

**Issue by TheArctesian** [vadimkorr/svelte-carousel#81]
Hey I'm trying to add text over an outplay carousel but it is hiding the h1 tag, idk if i did a fucky wucky or someting wrong w code. I just hopped on the svelte hype train so sorry if this is a stupid question. 

Code: 
Svelte

```Svelte 
<h1>
      some corpo stuff 
    </h1>
    <Carousel
		autoplay 
		autoplayDuration={5000} >
      <img src={heroImg1} alt="Welcome to Voiijer"/>
	  <img src="/Assets/imgs/hero/hero-any-desktop-gif.gif" alt="Welcome to Voiijer"/>
      <img src={heroImg2} alt="Welcome to Voiijer"/>
    </Carousel>
  </hero>
```

CSS 

```CSS
 h1 {
    position: absolute;
    width: 20%;
    text-align: left;
    font-weight: 600;
    line-height: 56px;
    left: 10%;
    top: 35%;
    font-size: 48px;
  }
  img {
    width: 100%;
    padding: none;
  }
  hero {
    width: 100%;
    border: none;
  }
// ya we can ignore how ugly this is for now 
```
